adjective1 = input("Enter a adjective word (how it looks, feels, or behaves)\t\t: ")
animal = input("Enter the name of any animal\t\t\t\t\t\t: ")
place = input("Enter a location or area where something can happen\t\t\t: ")
adjective2 = input("Enter a another adjective word (can be different from the first one)\t: ")
item = input("Enter a thing you can see or touch\t\t\t\t\t: ")
verb1 = input("Enter a verb\t\t\t\t\t\t\t\t: ")
verb2 = input("Enter a another verb\t\t\t\t\t\t\t: ")
adjective3 = input("Enter a adjective word how something happens\t\t\t\t: ")
emotion = input("Enter a word that describes a feeling\t\t\t\t\t: ")
verb3 = input("Enter an action the character does at the end\t\t\t\t: ")

print(f"\nOne day, a {adjective1} {animal} was walking through the {place}.")
print(f"Suddenly, it found a {adjective2} {item} lying on the ground.")
print(f"\nWithout thinking, the {animal} decided to {verb1} the {item}.")
print(f"This caused everyone nearby to {verb2} in a very {adjective3} way!")
print(f"\nIn the end, the {animal} felt very {emotion} and went home to {verb3}.\n")